version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: on-failure
    networks:
      - appnetwork

networks:
  aapnetwork:
