version: '3.8'
services:
  react-app:
    container_name: react_container
    image: react-app2-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    restart: on-failure
    networks:
      - appnetwork

networks:
  aapnetwork:
